services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870" # NameNode Web UI
      - "9000:9000" # HDFS RPC
    environment:
      - CLUSTER_NAME=retailchain
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - namenode:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    ports:
      - "9864:9864" # DataNode Web UI
    environment:
      - CLUSTER_NAME=retailchain
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - SERVICE_PRECONDITION=namenode:9000
    depends_on:
      - namenode
    volumes:
      - datanode:/hadoop/dfs/data

  spark-notebook:
    image: jupyter/pyspark-notebook:latest
    container_name: retailchain_pyspark
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/data
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      # IMPORTANT: prevents "Forbidden" after restart and makes login simple
      - JUPYTER_TOKEN=retailchain
    depends_on:
      - namenode
      - datanode

volumes:
  namenode:
  datanode:
